services:
  mysql:
    platform: linux/amd64
    image: mysql:8.3.0
    container_name: mysql.test.atdd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trade
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10