/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    java
    id("io.spring.dependency-management") version "1.1.4"
    id("org.springframework.boot") version "2.7.18"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:2021.0.9")
    }
}

dependencies {
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")
    testImplementation("org.projectlombok:lombok:1.18.30")
    testImplementation("com.fasterxml.jackson.core:jackson-annotations:2.16.2")
    testImplementation("org.assertj:assertj-core:3.25.3")

    testImplementation("org.reflections:reflections:0.10.2")
    testImplementation("com.mysql:mysql-connector-j:8.3.0")
    testImplementation("org.springframework.boot:spring-boot-starter-data-jpa")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.cloud:spring-cloud-starter-openfeign")
    testImplementation("io.cucumber:cucumber-java:7.15.0")
    testImplementation("io.cucumber:cucumber-spring:7.15.0")
    testImplementation("com.github.leeonky:DAL-java:0.5.1")
    testImplementation("com.github.leeonky:DAL-extension-basic:0.0.16")
    testImplementation("com.github.leeonky:jfactory:0.3.23")
    testImplementation("com.github.leeonky:jfactory-repo-jpa:0.1.14")
    testImplementation("com.github.leeonky:jfactory-cucumber:0.1.31")
}

tasks.bootJar {
    enabled = false
}

task("cucumber") {
    dependsOn("assemble", "testClasses")
    doLast {
        javaexec {
            val cucumberRuntime: Configuration by configurations.creating {
                extendsFrom(configurations["testImplementation"])
            }

            mainClass.set("io.cucumber.core.cli.Main")
            classpath = cucumberRuntime + sourceSets.main.get().output + sourceSets.test.get().output
            args = listOf(
                "--plugin", "pretty",
                "--glue", "cc.secondbrain.trade",
                "--glue", "com.github.leeonky.jfactory.cucumber",
                "src/test/resources"
            )
        }
    }
}
